import { Link } from 'react-router-dom';
import Header from '../components/Header';
import { AlertTriangle, ArrowLeft, FileWarning, Info } from 'lucide-react';

const disclaimerSections = [
  {
    title: 'Not medical advice',
    paragraphs: [
      'The information and insights provided by GutWise are for personal informational purposes only. Nothing in GutWise constitutes medical advice, a diagnosis, or a treatment recommendation.',
      'Always consult a qualified healthcare professional before making decisions about your health, diet, or treatment. Do not delay or disregard professional medical advice based on anything you see in GutWise.',
    ],
  },
  {
    title: 'No clinical relationship',
    paragraphs: [
      'Using GutWise does not create a relationship between you and any clinician or healthcare provider. Insights generated by the platform are produced by software, not by a licensed medical professional reviewing your case.',
    ],
  },
  {
    title: 'Emergencies',
    paragraphs: [
      'GutWise is not designed for emergencies. If you are experiencing severe or worsening symptoms, seek immediate medical attention by contacting your doctor or local emergency services.',
      'Do not use GutWise to manage an acute or urgent medical situation.',
    ],
  },
  {
    title: 'Insight accuracy',
    paragraphs: [
      'GutWise identifies patterns in your personal data. These patterns are generated automatically and reflect statistical associations, not clinical findings.',
      'Patterns may not apply to your individual circumstances. Your healthcare provider is the right person to help you interpret and act on any observation you find meaningful.',
    ],
  },
  {
    title: 'Dietary observations',
    paragraphs: [
      'Food-related observations in GutWise are based on the data you log and are general in nature. They are not personalized dietary prescriptions.',
      'If you have known food allergies, intolerances, a diagnosed condition, or are pregnant or nursing, consult a registered dietitian or your healthcare provider before changing your diet.',
    ],
  },
  {
    title: 'Limitation of liability',
    paragraphs: [
      'To the extent permitted by applicable law, GutWise and its team are not liable for any health outcomes, personal injury, or other harm arising from your use of the platform or reliance on any information it provides.',
    ],
  },
  {
    title: 'Responsible use',
    bullets: [
      'Use GutWise as a personal log and pattern-awareness tool, not as a clinical resource',
      'Share observations you find useful with your doctor or specialist',
      'Maintain regular care with your healthcare provider',
      'Report new or worsening symptoms to a medical professional promptly',
    ],
  },
  {
    title: 'Questions',
    paragraphs: [
      'If you have questions about this disclaimer, contact us through the in-app support channel. A dedicated contact address will be published before public launch.',
    ],
  },
];

export default function Disclaimer() {
  return (
    <div className="page-shell min-h-screen text-[var(--color-text-primary)]">
      <Header />

      <main id="main-content" tabIndex={-1} className="mx-auto max-w-4xl px-4 pb-14 pt-24 sm:px-6 sm:pt-28 lg:px-8">
        <div className="clinical-page-header">
          <Link
            to="/"
            className="motion-nav-link inline-flex w-fit items-center gap-2 text-sm font-semibold text-[var(--color-text-tertiary)] hover:text-[var(--color-text-secondary)]"
          >
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            Back to GutWise
          </Link>
          <span className="clinical-chip clinical-chip-caution w-fit">
            <Info className="h-4 w-4" aria-hidden="true" />
            Use boundaries
          </span>
          <div>
            <h1 className="text-3xl font-semibold tracking-[var(--gw-letter-spacing-tight)] text-[var(--color-text-primary)] sm:text-4xl">
              Medical Disclaimer
            </h1>
            <p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--color-text-secondary)]">
              Last updated: March 2026.
            </p>
          </div>
        </div>

        <section className="clinical-panel p-5 sm:p-6">
          <div className="rounded-[var(--gw-radius-card)] border border-[rgba(250,194,74,0.18)] bg-[rgba(250,194,74,0.075)] p-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 flex-shrink-0 text-[var(--gw-caution-200)]" aria-hidden="true" />
              <p className="text-sm font-semibold leading-6 text-[var(--color-text-primary)]">
                GutWise is a personal tracking and pattern-awareness tool. It is not a medical device,
                diagnostic platform, or substitute for professional care.
              </p>
            </div>
          </div>

          <div className="mt-7 space-y-8 text-sm leading-7 text-[var(--color-text-secondary)]">
            {disclaimerSections.map((section) => (
              <section key={section.title}>
                <div className="mb-3 flex items-center gap-2">
                  <FileWarning className="h-4 w-4 text-[var(--gw-brand-300)]" aria-hidden="true" />
                  <h2 className="text-base font-semibold text-[var(--color-text-primary)]">
                    {section.title}
                  </h2>
                </div>
                {section.paragraphs?.map((paragraph) => (
                  <p key={paragraph} className="mb-3 last:mb-0">
                    {paragraph}
                  </p>
                ))}
                {section.bullets && (
                  <ul className="list-disc space-y-2 pl-5">
                    {section.bullets.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
