import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Card from '../components/Card';
import { Info } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-neutral-bg dark:bg-dark-bg">
      <Header />

      <main id="main-content" tabIndex={-1} className="max-w-3xl mx-auto px-4 pb-12 pt-24 sm:px-6 lg:px-8">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <Info className="h-7 w-7 text-brand-500 dark:text-brand-300" />
            <h1 className="text-3xl font-sora font-semibold text-neutral-text dark:text-dark-text">Medical Disclaimer</h1>
          </div>
          <p className="text-sm text-neutral-muted dark:text-dark-muted">Last updated: March 2026</p>
        </div>

        <div className="rounded-xl border border-brand-300/30 dark:border-brand-700/30 bg-brand-100/20 dark:bg-brand-900/10 px-5 py-4 mb-6">
          <p className="text-sm text-neutral-text dark:text-dark-text font-medium">
            GutWise is a personal tracking and intelligence tool - not a medical device, diagnostic platform, or substitute for professional care.
          </p>
        </div>

        <Card>
          <div className="space-y-8 text-sm leading-relaxed text-neutral-muted dark:text-dark-muted">

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Not medical advice</h2>
              <p className="mb-3">
                The information and insights provided by GutWise are for personal informational purposes only. Nothing in GutWise constitutes medical advice, a diagnosis, or a treatment recommendation.
              </p>
              <p>
                Always consult a qualified healthcare professional before making decisions about your health, diet, or treatment. Do not delay or disregard professional medical advice based on anything you see in GutWise.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">No clinical relationship</h2>
              <p>
                Using GutWise does not create a relationship between you and any clinician or healthcare provider. The insights generated by the platform are produced by software, not by a licensed medical professional reviewing your case.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Emergencies</h2>
              <p className="mb-3">
                GutWise is not designed for emergencies. If you are experiencing severe or worsening symptoms, seek immediate medical attention — call your doctor or local emergency services.
              </p>
              <p>
                Do not use GutWise to manage an acute or urgent medical situation.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Insight accuracy</h2>
              <p className="mb-3">
                GutWise identifies patterns in your personal data. These patterns are generated automatically and reflect statistical associations, not clinical findings.
              </p>
              <p>
                Patterns may not apply to your individual circumstances. Your healthcare provider is the right person to help you interpret and act on any observation you find meaningful.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Dietary observations</h2>
              <p className="mb-3">
                Any food-related observations in GutWise are based on the data you log and are general in nature. They are not personalised dietary prescriptions.
              </p>
              <p>
                If you have known food allergies, intolerances, a diagnosed condition, or are pregnant or nursing, consult a registered dietitian or your healthcare provider before changing your diet.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Limitation of liability</h2>
              <p>
                To the extent permitted by applicable law, GutWise and its team are not liable for any health outcomes, personal injury, or other harm arising from your use of the platform or reliance on any information it provides.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">How to use GutWise responsibly</h2>
              <ul className="list-disc pl-5 space-y-1.5">
                <li>Use it as a personal log and pattern-awareness tool, not as a clinical resource</li>
                <li>Share observations you find useful with your doctor or specialist</li>
                <li>Maintain regular care with your healthcare provider</li>
                <li>Report any new or worsening symptoms to a medical professional promptly</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-semibold text-neutral-text dark:text-dark-text mb-3">Questions</h2>
              <p>
                If you have questions about this disclaimer, contact us through the in-app support channel. A dedicated contact address will be published before public launch.
              </p>
            </section>

          </div>
        </Card>

        <div className="mt-8 text-center">
          <Link to="/" className="text-sm text-brand-500 dark:text-brand-300 hover:text-brand-700 dark:hover:text-brand-100 font-medium transition-colors">
            Return to Home
          </Link>
        </div>
      </main>
    </div>
  );
}
