import type { UserDailyFeatures } from '../../types/dailyFeatures';

export function createDemoDailyFeature(
  date: string,
  overrides: Partial<UserDailyFeatures> = {}
): UserDailyFeatures {
  const base: UserDailyFeatures = {
    user_id: 'demo-user',
    date,
    event_count: 5,
    logging_completeness_score: 0.8,
    bm_count: 1,
    avg_bristol: 4,
    hard_stool_count: 0,
    loose_stool_count: 0,
    urgency_event_count: 0,
    incomplete_evacuation_count: 0,
    blood_present_count: 0,
    mucus_present_count: 0,
    first_bm_hour: 8,
    last_bm_hour: 8,
    symptom_event_count: 1,
    symptom_burden_score: 3,
    max_symptom_severity: 2,
    symptom_types: ['bloating'],
    meal_count: 3,
    food_item_names: ['oatmeal', 'coffee', 'salad'],
    food_tag_set: ['fiber'],
    ingredient_signals: ['fiber_dense'],
    gut_trigger_load: 1,
    high_fodmap_food_count: 0,
    dairy_food_count: 0,
    gluten_food_count: 0,
    artificial_sweetener_food_count: 0,
    high_fat_food_count: 0,
    spicy_food_count: 0,
    caffeine_food_count: 1,
    alcohol_food_count: 0,
    fiber_dense_food_count: 1,
    late_meal: false,
    hydration_total_ml: 2000,
    hydration_event_count: 4,
    hydration_raw_total_ml: 2300,
    hydration_water_goal_ml: 1600,
    hydration_caffeine_mg: 95,
    caffeine_beverage_count: 1,
    alcohol_beverage_count: 0,
    sleep_entry_count: 1,
    sleep_duration_minutes: 420,
    sleep_quality: 4,
    stress_event_count: 1,
    stress_avg: 3,
    stress_peak: 4,
    medication_event_count: 0,
    medications_taken: [],
    medication_families: [],
    medication_gut_effects: [],
    gi_risk_medication_count: 0,
    motility_slowing_medication_count: 0,
    motility_speeding_medication_count: 0,
    acid_suppression_medication_count: 0,
    microbiome_disruption_medication_count: 0,
    cycle_entry_count: 0,
    cycle_day: null,
    cycle_phase: null,
    exercise_minutes_total: 0,
    exercise_sessions_count: 0,
    moderate_vigorous_minutes: 0,
    movement_low_day: false,
    timezone: 'America/New_York',
  };

  return Object.assign(base, overrides, { date: overrides.date ?? date });
}
