/*
  # Create Insights and Reports Tables

  ## Overview
  This migration creates tables for storing generated health insights and user/system reports.
  These tables enable persistent storage of analysis results and customizable reporting.

  ## Tables Created

  ### 1. insight_snapshots
  Stores AI-generated or system-calculated health insights
  
  **Columns:**
  - `id` (uuid, primary key) - Unique insight identifier
  - `user_id` (uuid, not null) - References auth.users
  - `insight_type` (text, not null) - Type of insight (pattern, correlation, recommendation, alert)
  - `title` (text, not null) - Brief insight headline
  - `description` (text, not null) - Detailed insight explanation
  - `severity` (text) - Importance level (info, warning, critical)
  - `confidence_score` (numeric) - AI confidence level (0.0-1.0)
  - `data_sources` (jsonb) - References to source data that generated insight
  - `metadata` (jsonb) - Additional structured data (charts, statistics, etc.)
  - `date_range_start` (date) - Start of analysis period
  - `date_range_end` (date) - End of analysis period
  - `is_read` (boolean) - Whether user has viewed insight
  - `is_dismissed` (boolean) - Whether user dismissed insight
  - `created_at` (timestamptz) - When insight was generated
  - `updated_at` (timestamptz) - Last modification timestamp

  ### 2. reports
  Stores user-generated and system-generated health reports
  
  **Columns:**
  - `id` (uuid, primary key) - Unique report identifier
  - `user_id` (uuid, not null) - References auth.users
  - `report_type` (text, not null) - Type of report (summary, detailed, export, medical)
  - `title` (text, not null) - Report title
  - `description` (text) - Report purpose/context
  - `date_range_start` (date, not null) - Start of reporting period
  - `date_range_end` (date, not null) - End of reporting period
  - `format` (text, not null) - Output format (json, pdf, csv)
  - `status` (text, not null) - Generation status (pending, processing, completed, failed)
  - `content` (jsonb) - Report data structure
  - `file_url` (text) - URL to generated file (if applicable)
  - `filters` (jsonb) - Applied filters and parameters
  - `generated_at` (timestamptz) - When report was generated
  - `expires_at` (timestamptz) - When report/file should be deleted
  - `created_at` (timestamptz) - Record creation timestamp
  - `updated_at` (timestamptz) - Last modification timestamp

  ## Security Implementation

  ### Row Level Security (RLS)
  - **Enabled** on both tables
  - Each table has four policies: SELECT, INSERT, UPDATE, DELETE
  - All policies enforce user_id = auth.uid() for complete data isolation
  - Insights and reports are strictly private to each user

  ### Data Integrity
  - Foreign key constraints with CASCADE DELETE
  - Check constraints on severity and status enums
  - NOT NULL constraints on essential fields
  - Date range validation constraints
  - Automatic timestamp management

  ## Notes
  - Insights can be auto-generated by backend processes
  - Reports support multiple export formats
  - Metadata/content fields use JSONB for flexible storage
  - Confidence scores enable quality-based filtering
  - Expiration dates support automatic cleanup of old reports
  - Read/dismissed flags enable user interaction tracking
*/

-- Create insight_snapshots table
CREATE TABLE IF NOT EXISTS insight_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  insight_type text NOT NULL CHECK (insight_type IN ('pattern', 'correlation', 'recommendation', 'alert', 'trend')),
  title text NOT NULL,
  description text NOT NULL,
  severity text DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  confidence_score numeric(3, 2) CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
  data_sources jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  date_range_start date,
  date_range_end date,
  is_read boolean DEFAULT false,
  is_dismissed boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT valid_date_range CHECK (date_range_end IS NULL OR date_range_start IS NULL OR date_range_end >= date_range_start)
);

-- Create reports table
CREATE TABLE IF NOT EXISTS reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_type text NOT NULL CHECK (report_type IN ('summary', 'detailed', 'export', 'medical', 'custom')),
  title text NOT NULL,
  description text,
  date_range_start date NOT NULL,
  date_range_end date NOT NULL,
  format text NOT NULL CHECK (format IN ('json', 'pdf', 'csv', 'html')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  content jsonb,
  file_url text,
  filters jsonb DEFAULT '{}'::jsonb,
  generated_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT valid_report_date_range CHECK (date_range_end >= date_range_start)
);

-- Enable RLS on both tables
ALTER TABLE insight_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Insight Snapshots policies
CREATE POLICY "Users can view own insights"
  ON insight_snapshots FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own insights"
  ON insight_snapshots FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own insights"
  ON insight_snapshots FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own insights"
  ON insight_snapshots FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Reports policies
CREATE POLICY "Users can view own reports"
  ON reports FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own reports"
  ON reports FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own reports"
  ON reports FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own reports"
  ON reports FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Add updated_at triggers
CREATE TRIGGER update_insight_snapshots_updated_at
  BEFORE UPDATE ON insight_snapshots
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_reports_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_user_id ON insight_snapshots(user_id);
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_created_at ON insight_snapshots(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_user_created ON insight_snapshots(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_type ON insight_snapshots(insight_type);
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_severity ON insight_snapshots(severity);
CREATE INDEX IF NOT EXISTS idx_insight_snapshots_is_read ON insight_snapshots(user_id, is_read) WHERE is_read = false;

CREATE INDEX IF NOT EXISTS idx_reports_user_id ON reports(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_user_created ON reports(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_type ON reports(report_type);
CREATE INDEX IF NOT EXISTS idx_reports_generated_at ON reports(generated_at DESC) WHERE generated_at IS NOT NULL;